### PR TITLE
Feature/types

### PR DESCRIPTION
**Pull request by rayzor65**

### CODE REVIEW

**Comment by Denyllon** [comment]
hi @rayzor65 ,

Thank you for your request, but currently we're working on adding our official `d.ts` files to Highcharts. ETA is for now the 3rd quarter 2018 for the Beta.

Kind regards!

**Comment by TheJhonny007** [comment]
Is there an ETA for the release of official types?

**Comment by KacperMadej** [comment]
@TheJhonny007 https://github.com/highcharts/highcharts-react/pull/36#issuecomment-403001410

> ETA is for now the 3rd quarter 2018 for the Beta.

Here's more info: https://github.com/highcharts/highcharts/issues/4876

**Comment by TheJhonny007** [comment]
Yeah, I already found that, but will it also include types for highcharts-react?

**Comment by KacperMadej** [comment]
It will work for Highcharts. highcharts-react is a wrapper for Highcharts. The definitions for Highcharts will not cover this wrapper.

**Pull request closed without merging**
